name: Deploy to Firebase hosting

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Transpile
        run: |
          flutter build web

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_PWA_WEBSITE }}"
          projectId: flutter-pwa-website
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
